version: "3.3"
services:
        db:
                image: mariadb
                environment:
                        - MYSQL_ROOT_PASSWORD=#############
                        - MYSQL_USER=#############
                        - MYSQL_PASSWORD=##############
                        - MYSQL_DATABASE=e_app
        redis:
                image: redis
        e_api:
                image: e_app
                ports:
                        - "8032:8032"
                depends_on:
                        - migrate
                command: uwsgi --ini=uwsgi.ini
        e_ws:
                image: e_app
                ports:
                        - "8033:8033"
                depends_on:
                        - migrate
                        - redis
                        - e_beatserver
                command: daphne -b 0.0.0.0 -p 8033 E.asgi:application
        e_beatserver:
                image: e_app
                depends_on:
                        - redis
                command: /app/manage.py beatserver
        migrate:
                build: .
                image: e_app
                depends_on:
                        - db
                command: bash -c "/app/manage.py makemigrations base --noinput && /app/manage.py migrate --noinput"
