# Generated by Django 3.0.6 on 2020-09-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20200908_0730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesession',
            old_name='players',
            new_name='players_max',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='name',
            field=models.CharField(default='supercow', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamesession',
            name='password',
            field=models.CharField(blank=True, max_length=384),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='players_now',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='private',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
