# Generated by Django 3.0.6 on 2020-12-28 11:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200929_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 12, 28, 11, 14, 59, 437926, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamesession',
            name='finished',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='finished_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 28, 11, 15, 11, 319336, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamesession',
            name='started_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 28, 11, 15, 34, 433842, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SessionPlayerResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
                ('speed', models.FloatField()),
                ('mistake_ratio', models.FloatField()),
                ('team', models.CharField(blank=True, default='none', max_length=255)),
                ('winner', models.BooleanField()),
                ('correct_words', models.PositiveIntegerField()),
                ('incorrect_words', models.PositiveIntegerField()),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='base.Player')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='base.GameSession')),
            ],
        ),
    ]
