# Generated by Django 4.1.5 on 2023-01-24 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def rebind_user_ptrs(apps, schema_editor):
    Player = apps.get_model('base', 'Player')
    User = apps.get_model(settings.AUTH_USER_MODEL)
    for p in Player.objects.all():
        p.user = User.objects.get(id=p.pk)
        p.save()


def rebind_foreign_keys(apps, schema_editor):
    Player = apps.get_model('base', 'Player')
    GameSession = apps.get_model('base', 'GameSession')
    SessionPlayerResult = apps.get_model('base', 'SessionPlayerResult')
    for player in Player.objects.all().select_related('user'):
        # rebind GameSession->Player relation
        player_created_sessions = list(GameSession.objects.filter(old_creator=player.user.id))
        for s in player_created_sessions:
            s.creator = player
        GameSession.objects.bulk_update(player_created_sessions,
                                        fields=('creator',),
                                        batch_size=1000)
        # rebind SessionPlayerResult->Player relation
        player_finished_sessions = \
            list(SessionPlayerResult.objects.filter(old_player=player.user.id))
        for s in player_finished_sessions:
            s.player = player
        SessionPlayerResult.objects.bulk_update(player_finished_sessions,
                                                fields=('player',),
                                                batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_auto_20210227_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={},
        ),
        migrations.AlterModelManagers(
            name='player',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=False,
        ),
        migrations.RunPython(rebind_user_ptrs),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='creator',
            field=models.IntegerField(),
        ),
        migrations.RenameField(
            model_name='gamesession',
            old_name='creator',
            new_name='old_creator',
        ),
        migrations.AlterField(
            model_name='sessionplayerresult',
            name='player',
            field=models.IntegerField(),
        ),
        migrations.RenameField(
            model_name='sessionplayerresult',
            old_name='player',
            new_name='old_player',
        ),
        migrations.RemoveField(
            model_name='player',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='player',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamesession',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_created',
                                    to='base.player', null=True, blank=True),
        ),
        migrations.AddField(
            model_name='sessionplayerresult',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions',
                                    to='base.player', null=True, blank=True),
        ),
        migrations.RunPython(rebind_foreign_keys),
        migrations.RemoveField(
            model_name='gamesession',
            name='old_creator',
        ),
        migrations.RemoveField(
            model_name='sessionplayerresult',
            name='old_player',
        ),
    ]
