# Generated by Django 4.1.6 on 2023-02-05 18:07

from django.db import migrations, models
import uuid


def generate_session_ids(apps, schema_editor):
    GameSession = apps.get_model('base', 'GameSession')
    games = list(GameSession.objects.all())
    for game in games:
        game.session_id = uuid.uuid4()
    GameSession.objects.bulk_update(games, ('session_id',), batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_player_nickname_player_displayed_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesession',
            old_name='finished',
            new_name='is_finished',
        ),
        migrations.RenameField(
            model_name='gamesession',
            old_name='private',
            new_name='is_private',
        ),
        migrations.RenameField(
            model_name='gamesession',
            old_name='session_id',
            new_name='old_session_id',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='old_session_id',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.RunPython(generate_session_ids),
        migrations.AlterField(
            model_name='gamesession',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
