# Generated by Django 4.1.6 on 2023-02-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_finished_gamesession_is_finished_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddConstraint(
            model_name='gamesession',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('password', ''), ('is_private', False)), models.Q(models.Q(('password', ''), _negated=True), ('is_private', True)), _connector='OR'), name='force_password_for_private'),
        ),
    ]
