# Generated by Django 4.1.6 on 2023-02-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_sessionplayerresult_non_negative_speed'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sessionplayerresult',
            constraint=models.CheckConstraint(check=models.Q(('mistake_ratio__gte', 0)), name='non_negative_mistake_ratio'),
        ),
    ]
