# Generated by Django 4.1.6 on 2023-03-03 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_sessionplayerresult_non_negative_mistake_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sessionplayerresult',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='base.player'),
        ),
        migrations.AlterField(
            model_name='sessionplayerresult',
            name='team',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Stats',
        ),
    ]
