# Generated by Django 4.1.6 on 2023-03-03 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_gamesession_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionplayerresult',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='base.gamesession'),
        ),
    ]
