# Generated by Django 4.1.6 on 2023-03-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_sessionplayerresult_session'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gamesession',
            name='force_password_for_private',
        ),
        migrations.AddConstraint(
            model_name='gamesession',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('password', ''), ('is_private', False)), ('is_private', True), _connector='OR'), name='no_password_for_public'),
        ),
    ]
