# Generated by Django 4.2.1 on 2023-05-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_gamesession_force_password_for_private_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gamesession',
            name='no_password_for_public',
        ),
        migrations.AddConstraint(
            model_name='gamesession',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('password', ''), ('is_private', False)), ('is_private', True), _connector='OR'), name='no_password_for_public', violation_error_message="Can't set password on public Session"),
        ),
        migrations.AddConstraint(
            model_name='gamesession',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('finished_at', None), _negated=True), ('started_at', None), _negated=True), name='cant_be_finished_without_being_started', violation_error_message="Session can't be finished if it wasn't yet started"),
        ),
    ]
