# Generated by Django 4.1.6 on 2023-07-04 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_gamesession_cant_be_finished_without_being_started_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionplayerresult',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='base.player'),
        ),
    ]
