# Generated by Django 4.1.6 on 2023-07-04 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_sessionplayerresult_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionplayerresult',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='base.player'),
        ),
    ]
