# Generated by Django 4.1.6 on 2023-07-04 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_sessionplayerresult_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionplayerresult',
            old_name='team',
            new_name='team_name',
        ),
    ]
